### ISSUE TITLE
先检测能不能取到 atool-build 并给提示，现在直接报错不好理解

### ISSUE THREAD

**Issue by sorrycc** [dora-js/dora-plugin-webpack#2]
```
module.js:338
    throw err;
    ^

Error: Cannot find module 'atool-build/lib/mergeCustomConfig'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/private/tmp/mockjs/node_modules/dora-plugin-atool-build/lib/index.js:7:26)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by Keystion** [comment]
此bug并没有解决就关闭了？遇见类似问题不知道如何下一步。

**Comment by sorrycc** [comment]
npm install 时有 peerDependencies 提醒的。
